### PR TITLE
Test Nightwatch in workflows

### PR DESCRIPTION
**Pull request by mglaman**
Having this problem with a Dockerized chromedriver instance, which didn't happen before.

```
[Tests/Integration Test] Test Suite
===================================
- Connecting to chromedriver on port 9515...

    POST http://chromedriver:9515 /session - ECONNRESET
Error: socket hang up
    at connResetException (internal/errors.js:607:14)
⚠ Error connecting to chromedriver on port 9515.
_________________________________________________

TEST FAILURE: 1 error during execution; 0 tests failed, 0 passed (1m 0s)
  Error: An error occurred while retrieving a new session: "socket hang up"
```

Screen Shot 2021-03-22 at 12 05 05 PM

### CODE REVIEW

**Comment by mglaman** [comment]
Removing the `--log-path` will cause things to print to stderr

Per https://chromedriver.chromium.org/logging:

> You can also pass --log-path to cause the log to be written to a file instead of stderr.

**Comment by mglaman** [comment]
Found an error:

```
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
```

PHPUnit launch:

```
[1616476163.213][INFO]: Launching chrome: /usr/bin/google-chrome --disable-background-networking --disable-client-side-phishing-detection --disable-default-apps --disable-gpu --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-web-resources --enable-automation --enable-logging --force-fieldtrials=SiteIsolationExtensions/Control --headless --ignore-certificate-errors --load-extension=/tmp/.org.chromium.Chromium.xpMj6Z/internal --log-level=0 --metrics-recording-only --no-first-run --no-sandbox --password-store=basic --remote-debugging-port=12135 --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.org.chromium.Chromium.8yb60H data:,
```

Nightwatch

```
[1616476184.950][INFO]: Launching chrome: /usr/bin/google-chrome --disable-background-networking --disable-client-side-phishing-detection --disable-default-apps --disable-gpu --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-web-resources --enable-automation --enable-logging --force-fieldtrials=SiteIsolationExtensions/Control --headless --ignore-certificate-errors --load-extension=/tmp/.org.chromium.Chromium.ztsHGb/internal --log-level=0 --metrics-recording-only --no-first-run --password-store=basic --remote-debugging-port=12305 --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.org.chromium.Chromium.YGduT5 data:,
```

The differences is in `--remote-debugging-port` and `--no-sandbox` on PHPUnit.

```
--remote-debugging-port=12135
--remote-debugging-port=12305
```

**Comment by backlineint** [comment]
@mglaman if I change the `DRUPAL_TEST_BASE_URL` in `lando.yml` to one of the appserver URLs (DRUPAL_TEST_BASE_URL: 'http://nightwatch-training.lndo.site/' in this case) and then `lando rebuild` I'm able to get past the socket errors.

I also added --no-sanbox to the chrome_args, but I'm not sure if that matters

DRUPAL_TEST_WEBDRIVER_CHROME_ARGS: "--disable-gpu --headless --no-sandbox"

I now get the errors about not having PHP on the service, which I think you were expecting.

 ✖ Failed [fail]: (Command failed: php ./scripts/test-site.php install --setup-file "core/tests/Drupal/TestSite/TestSiteInstallTestScript.php" --install-profile "nightwatch_testing"  --base-url http://nightwatch-training.lndo.site/ --db-url mysql://drupal9:drupal9@database:3306/drupal9 --json
/bin/sh: 1: php: not found
)

**Comment by mglaman** [comment]
🤩 amazing. Thank you! Yeah, the tests need Node and PHP in the host/container.

I'll roll a commit with this shortly!

**Comment by mglaman** [comment]
THANK YOU @backlineint !

**Pull request merged**
